services:
  api:
    build: .
    ports:
      - '8000:8000'
    restart: "always"
    container_name: ke_service
    develop:
      watch:
        - action: rebuild
          path: .
          target: /code
          ignore: 
            - /code/notebooks/